### ISSUE TITLE
Continued Conversation

### ISSUE THREAD

**Issue by ripnonfegames** [ayush5harma/PixelFeatureDrops#10]
Recently, I got a Pixel 2XL, rooted it, and wanted the new Google Assistant 2.0 UI and  continued conversation. Found the XDA thread for it, and then found P4XLprops, flashed if, and I have 2 Errors...

1- Whenever I open Camera, It starts lagging like hell. Then it crashes after what, 5 seconds?

2- Google Assistant CC (Continued Conversation) Switch isn't available, but the UI shows immediately.

Camera Solved, 2 still needs answering

**Comment by ayush5harma** [comment]
1.It's a known **Issue**  with stock google camera there are only **Workarounds** which maybe adopted .
2.Continued Conversation is available for English(US) .

**Issue**: The module overrides existing prop values to spoof device to be Pixel4XL. Google camera uses these prop values but since the camera hardware is different in pixel2XL and 4XL it causes failure communicating with the hardware and thereby leading it  to crash.

**Workarounds**: 
1. Use cstark's Google Camera Port - https://www.celsoazevedo.com/files/android/google-camera/dev-cstark27/

2. If you use Edxposed Fraework on you device, you may make use of this module to fix stock Google Camera crash - https://github.com/ikws4/WeiJu

Here's how- 


![2020-10-01_00-53-15](https://user-images.githubusercontent.com/47772616/94730276-9bd42180-0380-11eb-9749-0949a01e1e8d.gif)

**Comment by ripnonfegames** [comment]
Hello, The Module fixed the error, as I was already using Camera PX port as it is superior.

About the Continued Conversation...
![Screenshot_20200930-182617](https://user-images.githubusercontent.com/56087561/94746413-a96eb480-034a-11eb-8cf2-33177c5bbda4.png)
There is no switch, as I said.

![Screenshot_20200930-192825](https://user-images.githubusercontent.com/56087561/94750029-30278f80-0353-11eb-8ddf-e7a4ff095a21.png)
And it IS on English (United States)

**Comment by ayush5harma** [comment]
Nice(though i still wonder what you mean  by saying module fixed it), now about the continued conversation, after changing the language to US English also clear the app data for toggle to appear.
You may check the video below (The toggle is not visible when my language is English (India) and on changing the language to English(US) it doesn't appear until google app's data is cleared).
![2020-10-01_11-30-49](https://user-images.githubusercontent.com/47772616/94773757-0b2a2f80-03da-11eb-9d8e-0c34b1d78790.gif)

**Comment by ripnonfegames** [comment]
Hello, Even though I do exactly that, no phone appears, I'm also wondering why it doesn't say downloading additional resources and just Setting up... The UI is working just fine but even with my assistant on English (United States) Still no phone, Does it depend on the country?

**Comment by ayush5harma** [comment]
It doesn't depend on the country although you should too check what you have set as you system language in settings.

**Comment by ripnonfegames** [comment]
I have seen multiple comments online it is only available in the US, Now I've turned the nav bar on and there is still no setting for GA 2.0 CC
![Screenshot_20201001-064731](https://user-images.githubusercontent.com/56087561/94800052-0e112a00-03b2-11eb-9206-92819c8238e1.png)

**Comment by ayush5harma** [comment]
> I have seen multiple comments online it is only available in the US, Now I've turned the nav bar on and there is still no setting for GA 2.0 CC
> ![Screenshot_20201001-064731](https://user-images.githubusercontent.com/56087561/94800052-0e112a00-03b2-11eb-9206-92819c8238e1.png)

It works for me in India , I hope this puts rest to all those comments And what do you mean by putting navbar on?

**Comment by ripnonfegames** [comment]
As of Nav bar, I mean the bar at the bottom, I AM using a root adblocker so I might disable that and try again

**Comment by ayush5harma** [comment]
> As of Nav bar, I mean the bar at the bottom, I AM using a root adblocker so I might disable that and try again

Both those things i.e the choice of  system navigation or adblocker won't have anything to do with it rather retry clearing data for the google app retrigger the assitant from home screen and visit the assistant settings from google app to check if it appears or not.

**Comment by ripnonfegames** [comment]
This is starting to get annoying, 
![Screenshot_20201001-070034](https://user-images.githubusercontent.com/56087561/94801483-1a968200-03b4-11eb-9964-0ad22143fddf.png)
It still isn't showing up, Do they not let CC where I am?

**Comment by ayush5harma** [comment]
No it doesn't depend on region as long as you choose to communicate with assistant in US english.
Try enrolling in google app beta testing but honestly that shouldn't be the case because continued conversation is there too in stable versions of google app still in case you want to enroll you can enroll by clicking join here - https://play.google.com/apps/testing/com.google.android.googlequicksearchbox
and then updating google app from playstore.

**Comment by ripnonfegames** [comment]
I have tried everything, and still. No GA 2.0.
Got into the beta program, reset data, did all of that shit.

I still don't know, what is going on.

**Comment by ayush5harma** [comment]
> I have tried everything, and still. No GA 2.0.
> Got into the beta program, reset data, did all of that shit.
> 
> I still don't know, what is going on.

Sorry that you had to do all that shit and this time you're saying you don't get GA 2.0 while before in this issue you said GA2 is there but no continue conversation toggle but again going by what you mention if you are not getting assistant v2 itself then refer the note for some pe and pe plus users in the readme.

**Comment by ripnonfegames** [comment]
Sorry, I do get the 2.0 UI, but for me the entire 2.0 is the CC because of its amazing features, while I only get the UI.
This is very annoying, as CC would help do a lot of things, this isn't your problem anymore, I'm going to ask Google Support for help.

**Comment by ripnonfegames** [comment]
Also PS, I am on Pixel 2 XL, not any custom roms

**Comment by ayush5harma** [comment]
> Also PS, I am on Pixel 2 XL, not any custom roms

Are you getting the updated google assistant post this module's installation ?

**Comment by ripnonfegames** [comment]
I am now. I wasn't able to before, What I am NOT getting is the continued Conversation, but I get the UI and everything else

**Comment by heykush** [comment]
i try to use latest cstark , it crashed and i also tried your framework but it still getting crashed, suggest me something and i for cc i have option but it's not working for me so i install march prop then cc start working. help me for cstark gcam

**Comment by ayush5harma** [comment]
> i try to use latest cstark , it crashed and i also tried your framework but it still getting crashed, suggest me something and i for cc i have option but it's not working for me so i install march prop then cc start working. help me for cstark gcam

cstark port is for pixel devices you need to find a port for your device that will work for you

**Comment by heykush** [comment]
I spoofed th latest cstark px now it's working thank you bro, solved both issues. hope in upcoimg update solve cc issue.
in setting button is showing but it's continue conversion is not working
