### ISSUE TITLE
Chrome colors has weird oversaturation overlay.

### ISSUE THREAD

**Issue by mecoromeo** [ayush5harma/PixelFeatureDrops#13]

**Comment by mecoromeo** [comment]
When I open chrome, it has this weird neon funky look. I try to screenshot it, but it just looks ok when I look at my gallery, but for some reason everytim I open the app, the colors are overly saturated, like those neon signs with color bleeding. FYI if I go to chrome settings it gets fixed, it's just in the home page and when I open a webpage that it happens. I don't know why

**Comment by mecoromeo** [comment]
I'm using Poco F1 Awaken OS 1.3 btw.

**Comment by iraniroahn** [comment]
> When I open chrome, it has this weird neon funky look. I try to screenshot it, but it just looks ok when I look at my gallery, but for some reason everytim I open the app, the colors are overly saturated, like those neon signs with color bleeding. FYI if I go to chrome settings it gets fixed, it's just in the home page and when I open a webpage that it happens. I don't know why

I am also facing the same issue ( using Awaken). Solved it by changing display Colors in settings to saturated. Hope it helps ;)

**Comment by mecoromeo** [comment]
> > When I open chrome, it has this weird neon funky look. I try to screenshot it, but it just looks ok when I look at my gallery, but for some reason everytim I open the app, the colors are overly saturated, like those neon signs with color bleeding. FYI if I go to chrome settings it gets fixed, it's just in the home page and when I open a webpage that it happens. I don't know why
> 
> I am also facing the same issue ( using Awaken). Solved it by changing display Colors in settings to saturated. Hope it helps ;)

That did it thank you

**Comment by iraniroahn** [comment]
Hey can you give your telegram id? I had some issues with props wanted to contact someone to know about issues
