### ISSUE TITLE
Google Camera Crashes when switched to video mode 

### ISSUE THREAD

**Issue by iraniroahn** [ayush5harma/PixelFeatureDrops#14]
Gcam Version: 6.2
ROM : Awaken OS 1.3 
Kernel: NGK 2.0

Whenever I try to switch to video mode on Google camera it freezes and then the whole app crashes. If I try to open any other app  which uses Camera ( snapchat) it too shows a blank screen a restart is required to solve this issue. 

This issue occurs only when recording 60fps videos

**Comment by ayush5harma** [comment]
Which gcam mod are u using? Iam guessing its builtin to the ROM. If so, then
- Try debloating the buitin gcam using **debloater** from magisk ( it will be under system priv-apps in the debloater list ).

- Install gcam mod by cstark : https://www.celsoazevedo.com/files/android/google-camera/dev-cstark27/

- Check it out if it works good then you can make it a system app too if you want but that's not needed.In case you want then use **app systemizer** from magisk for the same and move it to system priv-apps.

**Comment by iraniroahn** [comment]
__I tried using the gcam mod by cstark but it keeps crashing.I tried using PXv4.3_GoogleCamera_7.2.014.apk this version.__ Previously I was using gcam **MGC_6.2.030_RazerPhone2_V5.apk**( it wasn't built in) then I used **MGC 7.4.104 Parrot043-v5 Clone.apk** both were facing issues. 60 fps videos won't work + Images took longer to process and they turned out to be super warm.

**Comment by iraniroahn** [comment]
If possible do you know which version gcam to use ?
