### ISSUE TITLE
Face unlock

### ISSUE THREAD

**Issue by iraniroahn** [ayush5harma/PixelFeatureDrops#15]
Hey my Gcam issue is solved thank you very much! 

However I have another issue with Google assistant. I have the new ui however it doesn't have the Google color bar at the bottom and it doesn't work properly. Have attached screenshots below for a better understanding.

![Screenshot_20201117-095901_Google jpg](https://user-images.githubusercontent.com/34682394/99347136-4e722c00-28bc-11eb-88c0-8c3ec29dc79f.jpg)

**Comment by iraniroahn** [comment]
Please note:

1)Language set to : English US
2) Already cleared Google app data

**Comment by ayush5harma** [comment]
> Hey my Gcam issue is solved thank you very much!
> 
> However I have another issue with Google assistant. I have the new ui however it doesn't have the Google color bar at the bottom and it doesn't work properly. Have attached screenshots below for a better understanding.
> 
> ![Screenshot_20201117-095901_Google jpg](https://user-images.githubusercontent.com/34682394/99347136-4e722c00-28bc-11eb-88c0-8c3ec29dc79f.jpg)

It depends on the framework-res.apk  used by the custom ROM.Which custom ROM are you using ?

**Comment by iraniroahn** [comment]
I am using Awaken OS 1.3 on Poco F1

**Comment by ayush5harma** [comment]
> I am using Awaken OS 1.3 on Poco F1

It depends on the ROM build .This file is located at /system/framework .Even if i link you to framework.res apk for pixelUI it is not recommended to replace this file.

**Comment by iraniroahn** [comment]
So what's the solution? Wait for ROM dev to release update?

**Comment by ayush5harma** [comment]
it's not about rom update it's about the custom ROM itself.Some use google pixel's systemUI while some have their own just to provide more customizations.It may show up in another build though or you can try other custom ROMs.

**Comment by iraniroahn** [comment]
Oh okay thanks! Also...  Is there a telegram channel/group where you post updated props it would be really useful if you provide link/name

**Comment by 0xSK** [comment]
I believe your lack of colorful Google Assitant can be solved by following steps 4-7 of [this guide](https://forum.xda-developers.com/android/general/guide-how-to-eh-ne-t4094367)

**Comment by iraniroahn** [comment]
> I believe your lack of colorful Google Assitant can be solved by following steps 4-7 of [this guide](https://forum.xda-developers.com/android/general/guide-how-to-eh-ne-t4094367)

Thanks a lot this solved my problem! ;)

**Comment by ayush5harma** [comment]
@iraniroahn  Do you face issues with face unlock in this ROM with module installed?

**Comment by iraniroahn** [comment]
Yes I am Facing issues with face unlock it doesn't work. When tried to register face it opens the back-camera instead of the front infrared camera. ( using Poco F1) . Although didn't report as I don't use face unlock

**Comment by ayush5harma** [comment]
which face unlock is used in the ROM build ?

**Comment by iraniroahn** [comment]
One more issue that I face is with Widevine. Netflix shows certified L1 support and HDR however whenever I try to play an HDR 1080p video on Netflix it would never go above 480p.

Also on the YouTube app HDR colours are completely washed out.

**Comment by iraniroahn** [comment]
> which face unlock is used in the ROM build ?

Motorola Face unlock

**Comment by ayush5harma** [comment]
> One more issue that I face is with Widevine. Netflix shows certified L1 support and HDR however whenever I try to play an HDR 1080p video on Netflix it would never go above 480p.
> 
> Also on the YouTube app HDR colours are completely washed out.

For HDR in Netflix try patching using LuckyPatcher.

- Open The app menu in lucky patcher and download custom patches
- In the app list in lucky patcher select menu of patches and custom patch for Netflix 
- Apply and wait for it to patch then launch netflix and try playing 

Video -https://drive.google.com/file/d/1Yx5Z1lN1Y9ZWsC5lZ0Atyp63tv334rIG/view?usp=sharing

**Comment by ayush5harma** [comment]
> > which face unlock is used in the ROM build ?
> 
> Motorola Face unlock

can you tell the package name ?

**Comment by iraniroahn** [comment]
> > > which face unlock is used in the ROM build ?
> > 
> > 
> > Motorola Face unlock
> 
> can you tell the package name ?

![Screenshot_20201120-183203_Settings](https://user-images.githubusercontent.com/34682394/99803106-dc6d4180-2b5e-11eb-8647-7a1a751e78bb.png)

**Comment by iraniroahn** [comment]
> > > which face unlock is used in the ROM build ?
> > 
> > Motorola Face unlock
> 
> can you tell the package name ?

<Still capped at 480p :( applied the patches

**Comment by ayush5harma** [comment]
> > > > which face unlock is used in the ROM build ?
> > > 
> > > 
> > > Motorola Face unlock
> > 
> > 
> > can you tell the package name ?
> 
> <Still capped at 480p :( applied the patches

So on beryllium post module install following things are going out of order:
- face unlock that starts using back camera  instead of the IR setup
- hdr issue in netflix and youtube 
right? and they work when module is not active 
Can you attach build.prop files from your /system and system/vendor  folders

**Comment by iraniroahn** [comment]
Do you require only build.prop file or default.prop too?

**Comment by ayush5harma** [comment]
> Do you require only build.prop file or default.prop too?

only build.prop

**Comment by iraniroahn** [comment]
> > Do you require only build.prop file or default.prop too?
> 
> only build.prop

**Comment by iraniroahn** [comment]
> > Do you require only build.prop file or default.prop too?
> 
> only build.prop

build.prop:

https://drive.google.com/file/d/1cZ_WjFD0oFqbad6iXuIXYfkCS-bdPktY/view?usp=drivesdk

**Comment by ayush5harma** [comment]
> > > Do you require only build.prop file or default.prop too?
> > 
> > 
> > only build.prop
> 
> build.prop:
> 
> https://drive.google.com/file/d/1cZ_WjFD0oFqbad6iXuIXYfkCS-bdPktY/view?usp=drivesdk

Can you test this out 
[P4XLProps.zip](https://github.com/ayush5harma/P4XLProps/files/5575745/P4XLProps.zip)

**Comment by iraniroahn** [comment]
> > > > Do you require only build.prop file or default.prop too?
> > > 
> > > 
> > > only build.prop
> > 
> > 
> > build.prop:
> > https://drive.google.com/file/d/1cZ_WjFD0oFqbad6iXuIXYfkCS-bdPktY/view?usp=drivesdk
> 
> Can you test this out
> [P4XLProps.zip](https://github.com/ayush5harma/P4XLProps/files/5575745/P4XLProps.zip)

Tested it

Faceunlock still doesn't work
Also I am stuck with this weird bug where I have been logged out of my google account and whenever I try to sign in it doesn't let me in 

![Screenshot_20201121-110919_Google_Play_services](https://user-images.githubusercontent.com/34682394/99868611-0455b700-2bea-11eb-9ec5-014553944c84.png)

**Comment by iraniroahn** [comment]
> > > > > Do you require only build.prop file or default.prop too?
> > > > 
> > > > 
> > > > only build.prop
> > > 
> > > 
> > > build.prop:
> > > https://drive.google.com/file/d/1cZ_WjFD0oFqbad6iXuIXYfkCS-bdPktY/view?usp=drivesdk
> > 
> > 
> > Can you test this out
> > [P4XLProps.zip](https://github.com/ayush5harma/P4XLProps/files/5575745/P4XLProps.zip)
> 
> Tested it
> 
> Faceunlock still doesn't work
> Also I am stuck with this weird bug where I have been logged out of my google account and whenever I try to sign in it doesn't let me in
> 
> ![Screenshot_20201121-110919_Google_Play_services](https://user-images.githubusercontent.com/34682394/99868611-0455b700-2bea-11eb-9ec5-014553944c84.png)

Fixed the  Google account issue ( by removing the account and sign-in again)
