### ISSUE TITLE
Face unlock switched to back cam | Awaken 1.3 | Poco F1

### ISSUE THREAD

**Issue by mecoromeo** [ayush5harma/PixelFeatureDrops#16]
I'm not sure what happened, but when I initially installed the prop face unlock worked fine. For some reason it switched to using my back camera. Help pls

**Comment by ayush5harma** [comment]
Which ROM are you using ?

**Comment by mecoromeo** [comment]
Currently on Awaken 1.3 on a xiaomi poco F1

**Comment by ayush5harma** [comment]
Try this- https://github.com/ayush5harma/P4XLProps/issues/14
it might fix your issue if it is caused due to inbuilt gcam.

If not then only follow the following steps (which require edXposed):
1.Install module  **WeiJu** and activate it in the edxposed manager.
2. Enable showing system apps in it and add your face unlock to it.
3. Choose edit variables to override the prop values set my this module with your device default.
video for this - https://github.com/ayush5harma/P4XLProps/issues/10#issuecomment-701601857

**Comment by mecoromeo** [comment]
I tried both steps. The first one, installed gcam from the link you sent and kept crashing (previously using the latest parrot gcam 7.6). I then tried edxposed and kept me stuck in bootloop (used sandhook). I'll try yahfa and keep you updated and see if it works. Thanks.

Btw for pocof1 what should I edit (once i have weifu installed) and what to put. (Sorry beginner. Thank you)

**Comment by mecoromeo** [comment]
Tried both edxposed modules got stuck in loop. So both workarounds didn't work. Any other option? Thanks. If not that's fine

**Comment by ayush5harma** [comment]
> I tried both steps. The first one, installed gcam from the link you sent and kept crashing (previously using the latest parrot gcam 7.6). I then tried edxposed and kept me stuck in bootloop (used sandhook). I'll try yahfa and keep you updated and see if it works. Thanks.
> 
> Btw for pocof1 what should I edit (once i have weifu installed) and what to put. (Sorry beginner. Thank you)

Are you on android 11 from where did you install edxposed from? If on android R install edxposed from here 
: https://ci.appveyor.com/project/ElderDrivers/edxposed/builds/36319004/artifacts

**Comment by ayush5harma** [comment]
> I tried both steps. The first one, installed gcam from the link you sent and kept crashing (previously using the latest parrot gcam 7.6). I then tried edxposed and kept me stuck in bootloop (used sandhook). I'll try yahfa and keep you updated and see if it works. Thanks.
> 
> Btw for pocof1 what should I edit (once i have weifu installed) and what to put. (Sorry beginner. Thank you)

Did you debloat the built in gcam ?

**Comment by mecoromeo** [comment]
Yes A11 tried from magisk and then tried directly downloading from the latest from github and both didn't work

**Comment by ayush5harma** [comment]
> Yes A11 tried from magisk and then tried directly downloading from the latest from github and both didn't work

Yes both are meant for android Q .For android R you may use artifacts from the link above.
Did you debloat the builtin gcam ?
Debloat builtin gcam ,go to recovery to clear cache and dalvik  , re-enroll face and check it that fixes

**Comment by mecoromeo** [comment]
I tried installing the artifacts above but it kept saying riru not installed, even though i have riru 22.0 already installed. I'll try working on that and check on that dev but i guess for now i will stick to not having face unlock.

I've also tried talking with saikiran and reinz (dev and mainterner of the rom I'm using) and just waiting for their response and see if they can probably check on that for face unlock.

**Comment by ayush5harma** [comment]
> I tried installing the artifacts above but it kept saying riru not installed, even though i have riru 22.0 already installed. I'll try working on that and check on that dev but i guess for now i will stick to not having face unlock.
> 
> I've also tried talking with saikiran and reinz (dev and mainterner of the rom I'm using) and just waiting for their response and see if they can probably check on that for face unlock.

regarding edxposed you need to use riru 21.3 (https://github.com/RikkaApps/Riru/releases/download/v21.3/magisk-riru-v21.3.zip) and not 22 .Ik these things are complicated .Edxposed for riru 22 is a work in progress 
(https://github.com/ElderDrivers/EdXposed/pull/623)

_Debloat builtin gcam ,go to recovery to clear cache and dalvik , re-enroll face_ So this didn't work  ?

**Comment by mecoromeo** [comment]
I'll try again using 21.3. thanks for helping.

**Comment by mecoromeo** [comment]
![Screenshot_20201120-203356_Pixel_Launcher](https://user-images.githubusercontent.com/74412115/99801011-417d6300-2b70-11eb-82cc-c89eac0badc0.png)

Not sure if I did it correctly. But this is what I did. Also safety net is broken despite hiding everything in magisk hide even manager and hidden edxposed (from edxposed mañager) frok gms, and safetynet broken and phone became super slow and laggy. I'll close this case instead since its not worth having face unlock if the phone becomes unuseable

**Comment by ayush5harma** [comment]
> ![Screenshot_20201120-203356_Pixel_Launcher](https://user-images.githubusercontent.com/74412115/99801011-417d6300-2b70-11eb-82cc-c89eac0badc0.png)
> 
> Not sure if I did it correctly. But this is what I did. Also safety net is broken despite hiding everything in magisk hide even manager and hidden edxposed (from edxposed mañager) frok gms, and safetynet broken and phone became super slow and laggy. I'll close this case instead since its not worth having face unlock if the phone becomes unuseable

Safetynet it tippled because of edxposed.Riru 22 has an hiding mechanism which is gonna help in safetynet pass, and edxposed for riru 22 is being worked out .Nevertheless removing edxposed from magisk will fix safetynet and it'll also remove the lag so don't worry simply remove the edxposed.  

It seems the motorola package cannot access the from camera setup when using the module. I'll take a look at the default build.props used in building your rom for beryllium and adding the missing flags to P4XLProps.

**Comment by mecoromeo** [comment]
Oh ok. Yeah I just saw that iraniroahn has the same issue. He actually has the same phone and rom (awaken 1.3) if I'm not mistaken. If you need anything else let me know. Thanks

**Comment by mecoromeo** [comment]
I think this may be the culprit

ro.face.moto_unlock_service.cam_id=5

**Comment by ayush5harma** [comment]
> I think this may be the culprit
> 
> ro.face.moto_unlock_service.cam_id=5

Can you test this ?
<strike> [P4XLProps.zip](https://github.com/ayush5harma/P4XLProps/files/5574875/P4XLProps.zip) </strike>

added prop values from device_xiaomi_sdm845-common should fix the hdr and motorola face unlock.

**Comment by mecoromeo** [comment]
Hi. Tried flashing it but when I reboot i get stuck in the poco logo, won't proceed any further. I removed from and flashed on magisk again, this time i went to twrp first and cleared dalkiv and cache, still stuck in poco logo. Just wouldn't push beyond the poco logo

**Comment by ayush5harma** [comment]
> I think this may be the culprit
> 
> ro.face.moto_unlock_service.cam_id=5

Hi, sorry about that , can you try one more time ?
[P4XLProps-beryllium.zip](https://github.com/ayush5harma/P4XLProps/files/5575272/P4XLProps-beryllium.zip)

**Comment by mecoromeo** [comment]
![Screenshot_20201121-020638_Pixel_Launcher](https://user-images.githubusercontent.com/74412115/99834252-448f4800-2b9e-11eb-9cab-e64db7e74f18.png)
![Screenshot_20201121-020458_Pixel_Launcher](https://user-images.githubusercontent.com/74412115/99834272-4953fc00-2b9e-11eb-83a9-0f0d0d88f091.png)
![Screenshot_20201121-020519_Pixel_Launcher](https://user-images.githubusercontent.com/74412115/99834287-4e18b000-2b9e-11eb-9109-5842fc14a775.png)
![Screenshot_20201121-020634_Pixel_Launcher](https://user-images.githubusercontent.com/74412115/99834297-507b0a00-2b9e-11eb-9be7-5aa02333a8d8.png)

Tried flashing the new prop you gave and while I got in, the rear cam is still being used though

**Comment by ayush5harma** [comment]
> ![Screenshot_20201121-020638_Pixel_Launcher](https://user-images.githubusercontent.com/74412115/99834252-448f4800-2b9e-11eb-9cab-e64db7e74f18.png)
> ![Screenshot_20201121-020458_Pixel_Launcher](https://user-images.githubusercontent.com/74412115/99834272-4953fc00-2b9e-11eb-83a9-0f0d0d88f091.png)
> ![Screenshot_20201121-020519_Pixel_Launcher](https://user-images.githubusercontent.com/74412115/99834287-4e18b000-2b9e-11eb-9109-5842fc14a775.png)
> ![Screenshot_20201121-020634_Pixel_Launcher](https://user-images.githubusercontent.com/74412115/99834297-507b0a00-2b9e-11eb-9be7-5aa02333a8d8.png)
> 
> Tried flashing the new prop you gave and while I got in, the rear cam is still being used though

yes just added ro.face.moto_unlock_service.cam_id=5 as you and this  commit https://github.com/FreakyOS-Devices/device_xiaomi_beryllium/commit/6f19705be931df28f0fd5dca59459b05cc97913e suggested.
Can you sent your default build.prop at /system

**Comment by mecoromeo** [comment]
I uploaded the build.prop here

https://drive.google.com/folderview?id=13nalBR6Gh_25fCQm6SCdEhLV2NbN83Xb

**Comment by ayush5harma** [comment]
Check by adding the props related to camera  there are 4 of them  

ro.face.moto_unlock_service.cam_id=5
persist.vendor.camera.perfcapture=1
camera.disable_zsl_mode=true
vendor.camera.aux.packagelist=org.codeaurora.snapcam,com.android.camera,org.lineageos.snap,com.motorola.faceunlock

save the edit reboot and check if the fixes though iam confused myself as 

https://forum.xda-developers.com/nubia-z17/how-to/guide-enable-aux-camera-party-camera-t3846325/page2 

the above thread suggest aux to be the second back camera module but it's there in build.prop so worth trying adding it.

**Comment by mecoromeo** [comment]
Ok us this right?
![Uploading Screenshot_20201121-024500_Pixel_Launcher.png…]()

**Comment by mecoromeo** [comment]
![Uploading Screenshot_20201121-024500_Pixel_Launcher.png…]()

**Comment by mecoromeo** [comment]
![Uploading Screenshot_20201121-025029_Pixel_Launcher.png…]()
![Uploading Screenshot_20201121-024500_Pixel_Launcher.png…]()

**Comment by mecoromeo** [comment]
Still didn't work.

**Comment by mecoromeo** [comment]
Should I add # (hash)?

**Comment by ayush5harma** [comment]
those screenshots aren't uploaded so idk what was sent but no hash will comment that line

**Comment by mecoromeo** [comment]
![Uploading Screenshot_20201121-024500_Pixel_Launcher.png…]()

**Comment by mecoromeo** [comment]
![Uploading Screenshot_20201121-024500_Pixel_Launcher.png…]()

**Comment by mecoromeo** [comment]
![Uploading Screenshot_20201121-024500_Pixel_Launcher.png…]()

**Comment by ayush5harma** [comment]
it's still the same uploading 
![image](https://user-images.githubusercontent.com/47772616/99839632-0d666a00-2b91-11eb-897d-3bc50e133ac6.png)
You must have added it right bro maybe just try clearing the dalvik cache from recovery or something else need to  done to fix it .If you use face unlock often remove the pixelprop module for the time being ..

**Comment by mecoromeo** [comment]
Not sure why it's not uploading. My internet works fine though. Anyway i unzipped, then added it in the system.prop then zipped again. All works fine except face unlock still

ro.face.moto_unlock_service.cam_id=5
persist.vendor.camera.perfcapture=1
camera.disable_zsl_mode=true
vendor.camera.aux.packagelist=org.codeaurora.snapcam,com.android.camera,org.lineageos.snap,com.motorola.faceunlock

**Comment by mecoromeo** [comment]
> it's still the same uploading
> ![image](https://user-images.githubusercontent.com/47772616/99839632-0d666a00-2b91-11eb-897d-3bc50e133ac6.png)
> You must have added it right bro maybe just try clearing the dalvik cache from recovery or something else need to done to fix it .If you use face unlock often remove the pixelprop module for the time being ..

Ok no problem. Thanks for the help

**Comment by ayush5harma** [comment]
> Not sure why it's not uploading. My internet works fine though. Anyway i unzipped, then added it in the system.prop then zipped again. All works fine except face unlock still
> 
> ro.face.moto_unlock_service.cam_id=5
> persist.vendor.camera.perfcapture=1
> camera.disable_zsl_mode=true
> vendor.camera.aux.packagelist=org.codeaurora.snapcam,com.android.camera,org.lineageos.snap,com.motorola.faceunlock

You did't have to repack if the module is already flashed the system.prop file will be at /data/adb/modules/P4XLProps/system.prop
you can make a change directly to this file then save and reboot.

**Comment by mecoromeo** [comment]
I kept digging a bit and I'd like to ask if "ro.product.system.manufacturer=Google" is necessary for NGA? Because The reason I flashed the prop is to get NGA. 

Now, as I said I kept digging and found a different prop By Elon Musk, and found that his prop doesn't break face unlock and as noted in his git page that it's only for widevine L1 and not NGA. Long story short, I checked his prop and found that he did this:

#ro.product.system.manufacturer=Google
ro.product.system.manufacturer=Xiaomi

I tried it (although his redfin prop was only for september so safetynet fails since my rom is november patch) and it is spoofing as pixel 5 and it didn't break face unlock but aside from safetynet it didn't give me NGA.

Do you think this could work? Or is that manufacturer line necessary for NGA? Thanks

**Comment by mecoromeo** [comment]
I'm not sure though if I have to make all "ro.product.system.manufacturer=Google" line as a comment and add "ro.product.system.manufacturer=Xiaomi" line below each google manufacturer line

**Comment by ayush5harma** [comment]
> I kept digging a bit and I'd like to ask if "ro.product.system.manufacturer=Google" is necessary for NGA? Because The reason I flashed the prop is to get NGA.
> 
> Now, as I said I kept digging and found a different prop By Elon Musk, and found that his prop doesn't break face unlock and as noted in his git page that it's only for widevine L1 and not NGA. Long story short, I checked his prop and found that he did this:
> 
> #ro.product.system.manufacturer=Google
> ro.product.system.manufacturer=Xiaomi
> 
> I tried it (although his redfin prop was only for september so safetynet fails since my rom is november patch) and it is spoofing as pixel 5 and it didn't break face unlock but aside from safetynet it didn't give me NGA.
> 
> Do you think this could work? Or is that manufacturer line necessary for NGA? Thanks

No it won't enable the NGA as the google app reads all these values from the build.prop file to enable the NGA.

<strike>[P4XLProps.zip](https://github.com/ayush5harma/P4XLProps/files/5575745/P4XLProps.zip)
(added device/xiaomi/sdm845-common values from your original build.prop hope doesn't end you up in bootloop and fix the face unlock )</strike>

**Comment by mecoromeo** [comment]
The last commented prop didn't work too. No worries though, I'll keep using the prop, I can live without face unlock for now. The pixel prop has more benefits for me than face unlock. Thanks
