### ISSUE TITLE
google ar services didn't work

### ISSUE THREAD

**Issue by vidhitchauhann** [ayush5harma/PixelFeatureDrops#19]
I tried it on pixel reloaded caf which is almost same as pixel experience in ui and features wise, but after flashing December hal3 zip, some features are working but google ar services is still not showing on playstore

**Comment by ayush5harma** [comment]
Clear playstore data and check.
If not check whether camera hal3 is enabled or not using app like cam2api probe.

**Comment by vidhitchauhann** [comment]
it worked! btw will google assistant 2.0 okay google features work with this props? or do I've to manually open the assistant

**Comment by ayush5harma** [comment]
It works for English(US) and English (UK), will also be there for others as Google rolls it out. Option to enable voice match will be there inside Google app settings if voice match is available for the language.

Although there's another issue faced sometimes by some where voice match toggle keeps turning off by itself. 

https://amp.reddit.com/r/GooglePixel/comments/9vn5hm/access_with_voice_match_switching_off_every_time/

If that happens just try clearing google app data and all should work good.
