### ISSUE TITLE
NO new assistant ui 

### ISSUE THREAD

**Issue by heykush** [ayush5harma/PixelFeatureDrops#2]
Guide as to use new google assistant

**Comment by ayush5harma** [comment]
Flash the module, clean Google app's data and launch Google assistant.It will ask to download additional update.
Also mention the custom ROM you're using.

**Comment by heykush** [comment]
I'm using pixel experience plus in my redmi note 5(vince) but still not able to get new ui

**Comment by ayush5harma** [comment]
> I'm using pixel experience plus in my redmi note 5(vince) but still not able to get new ui

These may be possible causes:

- **Mismatch between device security patch and module release patch**:Which month's P4XLProps zip did you flash?Ensure that you've flashed the zip corresponsing to custom rom's security patch date.(For example if your ROM is on  5th May security patch, flash the May release of module).
- **Module isn't installed(happens if using old magisk manager due to magisk template change since magisk version 19)**:Ensure using latest magisk to flash.If using old magisk manager you can simply download and paste the module's  folder available here -  https://drive.google.com/drive/folders/1S7rWc-4KyH6NlWrTcmdeYZX1GPmWhalH?usp=sharing  
 into /data/adb/modules to enable the module.
- **Missing ngaresources apk(least likely in gapps builds of custom roms)**:Check whether other features which require additional download are working for you  or not like live transcribe.If not, then it's because of missing ngaresources apk which is used to make these additional downloads (and this comes preinstalled in the gapps build of recent custom rom's including PE)

**Comment by heykush** [comment]
I'll try all this cause

**Comment by heykush** [comment]
when is June Update come?

**Comment by ayush5harma** [comment]
> I'll try all this cause

Also make sure your langage is set to English(US)  and not English(India).

**Comment by ayush5harma** [comment]
> when is June Update come?

Your device vince hasn't got june build yet from pixelexperience, you shouldn't flash the june release of module that'll lead to cts profile failure in safetynet .Wait for pe plus june build then flash it and regarding your issue:
- Check language being set to English (US).
- Check security patch of the ROM and flash the release zip of that month accordingly.
- Clean google apps data and launch assistant which will ask to download additional update around 42MB to enable the new assistant.

**Comment by heykush** [comment]
yes, i'll take care of all procedure and will flash june patch after the release of june pe . let know what happen next..

**Comment by ayush5harma** [comment]
> > I'm using pixel experience plus in my redmi note 5(vince) but still not able to get new ui
> 
> These may be possible causes:
> 
> * **Mismatch between device security patch and module release patch**:Which month's P4XLProps zip did you flash?Ensure that you've flashed the zip corresponsing to custom rom's security patch date.(For example if your ROM is on  5th May security patch, flash the May release of module).
> * **Module isn't installed(happens if using old magisk manager due to magisk template change since magisk version 19)**:Ensure using latest magisk to flash.If using old magisk manager you can simply download and paste the module's  folder available here -  https://drive.google.com/drive/folders/1S7rWc-4KyH6NlWrTcmdeYZX1GPmWhalH?usp=sharing
>   into /data/adb/modules to enable the module.
> * **Missing ngaresources apk(least likely in gapps builds of custom roms)**:Check whether other features which require additional download are working for you  or not like live transcribe.If not, then it's because of missing ngaresources apk which is used to make these additional downloads (and this comes preinstalled in the gapps build of recent custom rom's including PE)

- Missing NgaResources :NgaResources is missing in recent PE builds causing trouble downloading additional assitant update.
It Can be installed from the link below:
https://drive.google.com/file/d/1fTymlp9KaeTinK2D_UqAJUmaGwexeEz-/view

**Comment by heykush** [comment]
what is Nga Resources??
is it safe to install?

**Comment by ayush5harma** [comment]
> what is Nga Resources??
> is it safe to install?

- It is needed to download resources such as assistant upgrade, pokemon live wallpaper et  cetera.It comes preinstalled in pixel 4 and 4xl as system-priv app and also in most custom ROM's which included PE till now.
- If it's preinstalled for you then there is no need to sideload and infact it won't sideload ,if not then yes  it's safe to sideload that apk and  should be done.

**Comment by Viraj8456** [comment]
For those who tries to trigger assistant but nothing pops up, but it is listening and replying like normal...

I don't know if it actually works but a July 1st Google Play system update solved my problem.

![Screenshot_20200808-121128853](https://user-images.githubusercontent.com/36239072/89727356-80642e80-da41-11ea-918f-e6c914382f5d.jpg)
.. 
![Screenshot_20200808-122807414](https://user-images.githubusercontent.com/36239072/89727334-45fa9180-da41-11ea-9ae1-4f02bf9e6f13.jpg)

**Comment by sanjeevstunner** [comment]
No ui popup in google assistant, December 2020, all apps updated, nga Installed, but no glowing popup, but assistant still listens to my commands

**Comment by ayush5harma** [comment]
> No ui popup in google assistant, December 2020, all apps updated, nga Installed, but no glowing popup, but assistant still listens to my commands

--> https://github.com/ayush5harma/PixelFeatureDrops/issues/21
