### ISSUE TITLE
Bootloops/essential prop tweaks

### ISSUE THREAD

**Issue by brian6932** [ayush5harma/PixelFeatureDrops#20]
I wanted to know which specific build prop tweaks used in this module enable Hold For Me and Call Screening, do I have spoof my phone's fingerprint to get these features? If possible, I wouldn't want to spoof my phone's fingerprint, I currently use the xmlpak module as my fingerprint modifier. Installing this module causes bootloops for me.

For reference I'm on an Essential PH1 on Android 10, using the stock ROM/AOSP

**Comment by ayush5harma** [comment]
Hold for me and call screening options are available as flag options for google dialer at
/data/data/com.google.android.dialer/shared_prefs/dialer_phenotype_flags.xml

However turning their boolean values to true doesn't work as on launching dialer it checks for device fingerprint and reset these flags.

A workaround would be to change the flags and then change permission of 
dialer_phenotype_flags.xml so that dialer won't be able to write changes into it.

Regarding spoofing phone's fingerprint, it uses  Pixel 5's fingerprint as mentioned in the readme. And requires android R as mentioned which caused you a bootloop.

**Comment by brian6932** [comment]
> Hold for me and call screening options are available as flag options for google dialer at
> /data/data/com.google.android.dialer/shared_prefs/dialer_phenotype_flags.xml

> A workaround would be to change the flags and then change permission of
> dialer_phenotype_flags.xml so that dialer won't be able to write changes into it.

How do you go about doing these?

**Comment by brian6932** [comment]
https://github.com/thehappydinoa/google-call-screening does this work?

**Comment by ayush5harma** [comment]
> > Hold for me and call screening options are available as flag options for google dialer at
> > /data/data/com.google.android.dialer/shared_prefs/dialer_phenotype_flags.xml
> 
> > A workaround would be to change the flags and then change permission of
> > dialer_phenotype_flags.xml so that dialer won't be able to write changes into it.
> 
> How do you go about doing these?

I don't understand .Like how to edit and change permissions? You can use any file explorer that allows accessing root partitions like Xplore or any other of your choice.

**Comment by ayush5harma** [comment]
> https://github.com/thehappydinoa/google-call-screening does this work?

I don't think it would as the flag values have been changed since then .So it's better to do it manually.

**Comment by brian6932** [comment]
![image](https://user-images.githubusercontent.com/18603393/103434614-ff652980-4bd1-11eb-8c8f-627df951b5f2.png)
what would I change these values to?

**Comment by ayush5harma** [comment]
You may try changing the permission of the folder "shared_prefs"  to 551 (dr-xr-x--x)

**Comment by ayush5harma** [comment]
> ![image](https://user-images.githubusercontent.com/18603393/103434614-ff652980-4bd1-11eb-8c8f-627df951b5f2.png)
> what would I change these values to?

![Screenshot_2021-01-01-12-17-23-71.jpg](https://user-images.githubusercontent.com/47772616/103434727-564b1d00-4c2b-11eb-861b-f6d1eba3048a.jpg)

**Comment by ayush5harma** [comment]
> > ![image](https://user-images.githubusercontent.com/18603393/103434614-ff652980-4bd1-11eb-8c8f-627df951b5f2.png)
> > what would I change these values to?
> 
> ![Screenshot_2021-01-01-12-17-23-71.jpg](https://user-images.githubusercontent.com/47772616/103434727-564b1d00-4c2b-11eb-861b-f6d1eba3048a.jpg)

For the shared_pref folder itself.

**Comment by brian6932** [comment]
ah ok, I'll try it

**Comment by brian6932** [comment]
Ok, so I tried it and it didn't work, do I have to check recursive?

**Comment by brian6932** [comment]
![image](https://user-images.githubusercontent.com/18603393/103434816-7996ad80-4bd4-11eb-83f2-cc2ba4fd00cf.png)
This is what it looks like rn

**Comment by brian6932** [comment]
Ok so I checked recursive and it still doesn't work

**Comment by ayush5harma** [comment]
> Ok so I checked recursive and it still doesn't work

You changed flag values related to call screening  in  dialer_phenotype_flags.xml then set the permission of 'shared_prefs' folder to 551 and force stopped dialer and relaunched it right?
