### ISSUE TITLE
No assistant UI | POSP+NikGapps | Redmi Note 6 Pro

### ISSUE THREAD

**Issue by sanjeevstunner** [ayush5harma/PixelFeatureDrops#21]
No ui popup in google assistant, December 2020, all apps updated, nga Installed, but no glowing popup, but assistant still listens to my commands

https://user-images.githubusercontent.com/42514333/103486484-44809a00-4e24-11eb-9264-aa4850bcb2eb.mp4

**Comment by ayush5harma** [comment]
> No ui popup in google assistant, December 2020, all apps updated, nga Installed, but no glowing popup, but assistant still listens to my commands
> 
>  screen-20210104-003157.mp4

https://github.com/ayush5harma/PixelFeatureDrops/issues/15#issuecomment-730145041

If this solves for you mention the custom ROM that you are using.

**Comment by sanjeevstunner** [comment]
I already checked that issue and tried everything, but no results. I'm using posp unofficial android 11 build on my redmi note 6 pro.

**Comment by ayush5harma** [comment]
> I already checked that issue and tried everything, but no results. I'm using posp unofficial android 11 build on my redmi note 6 pro.

is it gapps build?

**Comment by sanjeevstunner** [comment]
Nope, but flashed Nik gapps full on top of it

**Comment by ayush5harma** [comment]
> Nope, but flashed Nik gapps full on top of it

it worked till Novemeber ?  
If this is the first time you flashed the module , it would be hazzlefree on gapps builds and so is suggested. Custom gapps have their own issues with custom roms.   
Or try flashing other gapp packages like flame or bitgapps.

**Comment by sanjeevstunner** [comment]
It was the first time I'm flashing the package, will try flashing other gapps package on top

**Comment by ayush5harma** [comment]
moved to  https://github.com/ayush5harma/PixelFeatureDrops/issues/25
