### ISSUE TITLE
December version would disabled front wide angle camera on Pixel 3

### ISSUE THREAD

**Issue by Hmmmmmmmmmm** [ayush5harma/PixelFeatureDrops#22]
Device: Google Pixel 3
ROM: stock ROM, Dec update, android 11

After flash this module, play store ask me to update several apps including **device health services**, which turn immediately stopped after update. I'm guessing this is the reason why Google camera can't access the right angle camera in the front of pixel 3.

I can provide more information for you, comment below and thanks for your contribution! It really helps me a lot

**Comment by ayush5harma** [comment]
**device health services** is crashing ?

**Comment by Hmmmmmmmmmm** [comment]
> **device health services** is crashing ?

Corret. Here's a screenshot for it.
![image](https://user-images.githubusercontent.com/28838634/104092152-0f10fc00-52bd-11eb-80b6-bbde3c27382d.png)

**Comment by ayush5harma** [comment]
> > **device health services** is crashing ?
> 
> Corret. Here's a screenshot for it.
> ![image](https://user-images.githubusercontent.com/28838634/104092152-0f10fc00-52bd-11eb-80b6-bbde3c27382d.png)

Is the camera issue still there with recent releases?

**Comment by Hmmmmmmmmmm** [comment]
> > > **device health services** is crashing ?
> > 
> > 
> > Corret. Here's a screenshot for it.
> > ![image](https://user-images.githubusercontent.com/28838634/104092152-0f10fc00-52bd-11eb-80b6-bbde3c27382d.png)
> 
> Is the camera issue still there with recent releases?

Wasn't able to OTA my device to Feb update with Magisk new OTA policy, but i flashed Feb version of this module anyway.
Can confirm the prompt says device health services crashed still stays with new release of this module; and wide-angle camera still fails to open.

Will post another update if i managed to OTA devices and use the correct version.
