### ISSUE TITLE
Support for adaptive charging and extreme battery saver on pixel 2?

### ISSUE THREAD

**Issue by Kalyan-M** [ayush5harma/PixelFeatureDrops#23]
As the title says, does this add support for adaptive charging and extreme battery saver for older pixel devices?

**Comment by ayush5harma** [comment]
Yes after installing the module, install app updates from playstore which will also update **settings suggestions** and related apps and extreme battery saver option should appear in the settings.

The module adds necessary xml file for adaptive charging although how good adaptive charging is is debatable -https://www.xda-developers.com/google-pixel-adaptive-charging-details/

However none is tested on stock ROM by me, so see if it works for you. Another issue which is reported in stock pixel was with google camera, so if you face the same then it's suggested to use gcam port by cstark instead : https://www.celsoazevedo.com/files/android/google-camera/dev-cstark27/

**Comment by karan439** [comment]
I am on stock rom Pixel 2XL. Could you please clarify if it's okay to install Dec/Jan release for the newer features and still pass CTS?

**Comment by ayush5harma** [comment]
> I am on stock rom Pixel 2XL. Could you please clarify if it's okay to install Dec/Jan release for the newer features and still pass CTS?

Assuming that you are passing CTS as of now then you only need to check the security patch your ROM is on from settings and install the appropriate magisk module.  

https://github.com/ayush5harma/PixelFeatureDrops#instructions-for-installation-    

https://github.com/ayush5harma/PixelFeatureDrops#instructions-for-safetynet-

**Comment by karan439** [comment]
The security patch on my rom is from Oct. Does that imply I can only enable features upto Oct?

**Comment by ayush5harma** [comment]
> The security patch on my rom is from Oct. Does that imply I can only enable features upto Oct?

yes
