### ISSUE TITLE
No assistant UI | Redmi Note 6 pro | Octavi os 1.4 | gapps inbuilt

### ISSUE THREAD

**Issue by sanjeevstunner** [ayush5harma/PixelFeatureDrops#25]
Installed nga resources, Cleared data for google app

**Comment by sanjeevstunner** [comment]
Already raised a issue for posp with Nik gapps, on December patch mod

**Comment by ayush5harma** [comment]
Usually in gapps builds ngaresources apk is preinstalled system app however as you say you had to install it so it was missing in your gapps build.If missing nga configurations caused this then following should fix your issue: 
If your ROM is updated for February Patches try out the latest release to check if it works or not- https://github.com/ayush5harma/PixelFeatureDrops/releases/tag/r6
If on Jan Patch try this - 
[PixelFeatureDrop-January.zip](https://github.com/ayush5harma/PixelFeatureDrops/files/5938526/PixelFeatureDrop-January.zip)
If on Dec Patch try this -
[PixelFeatureDrop-December.zip](https://github.com/ayush5harma/PixelFeatureDrops/files/5938531/PixelFeatureDrop-December.zip)


and tell whether this fixes your assistant UI issue.(Clear google app's data after flashing)

--------------------------------------------------------------------------------------------------------
continued issues -https://github.com/ayush5harma/PixelFeatureDrops/issues/21 https://github.com/ayush5harma/PixelFeatureDrops/issues/15#issuecomment-730145041

**Comment by ayush5harma** [comment]
Use PixelFeatureDrop-Month-portedGA2 for such cases
