### ISSUE TITLE
Assistant 2.0 not working

### ISSUE THREAD

**Issue by YKSGaming** [ayush5harma/PixelFeatureDrops#26]
It says it is downloading the resources when I first start Google Assistant, but I only got the compact assistant. 
Device: Pixel 2 XL
ROM: Evolution X 5.2 (Android 11)

**Comment by YKSGaming** [comment]
Using default gapps that come with evoX, and also no adaptive charging. Adaptive sound works tho. Keep up the good work!

**Comment by ayush5harma** [comment]
If your ROM is updated for February Patches try out the latest release - https://github.com/ayush5harma/PixelFeatureDrops/releases/tag/r6
If on Jan Patch try this - 
[PixelFeatureDrop-January.zip](https://github.com/ayush5harma/PixelFeatureDrops/files/5938526/PixelFeatureDrop-January.zip)

to check if it works  now or not.

Clear google app's data after flashing.

**Comment by YKSGaming** [comment]
Thanks!

**Comment by ayush5harma** [comment]
> Thanks!

Worked?

**Comment by Viraj8456** [comment]
I'm using Potter and your Feb Pixel FD module, and assistant 2.0 is not working here... It's still a ghost.. it can reply but doesn't show up... 
ROM : PE11

**Comment by YKSGaming** [comment]
> > Thanks!
> 
> Worked?

Worked mostly, but the UI and the animation are quite bugged.

https://photos.app.goo.gl/yYKd6oQuMJvB5pKXA

**Comment by ayush5harma** [comment]
Hi, can you both confirm that your language in assistant is set to English (United States) and only that no other language in addition. Just to know if the disappearance of color bar compact look at the bottom is related to that.

**Comment by Viraj8456** [comment]
Primary was English US... Secondary was English India...

**Comment by ayush5harma** [comment]
> Primary was English US... Secondary was English India... 

Can you check keeping only English (US) removing English (India)

**Comment by Viraj8456** [comment]
Tried it... Still not working... Now I'm in March patch and safety net failed after installed this module...

**Comment by ayush5harma** [comment]
safetynet failure due to hardware attestation fix - https://github.com/ayush5harma/PixelFeatureDrops#instructions-for-safetynet-
