### ISSUE TITLE
Unable to use adaptive charging, adaptive sound

### ISSUE THREAD

**Issue by hehedemuse** [ayush5harma/PixelFeatureDrops#27]
@ayush5harma My device is Redmi 4X, which is installed lineageos 18.1, After flashing your module, these functions are not available, and you can't find it in the settings.

**Comment by ayush5harma** [comment]
Adaptive Sound appear under settings after installing the module(https://github.com/ayush5harma/PixelFeatureDrops#instructions-for-installation-) and updating apps from playstore which will install settings suggestions , device personalization services and all what's needed.

Try with AOSP based custom ROM using pixel UI.

**Comment by Viraj8456** [comment]
I'm using pixel experience+ Android 11... I'm having the same issue...
Device: Potter
Module: March

**Comment by Kalyan-M** [comment]
Can confirm, not working on PixelExperience with March security patch. (Pixel 2)

**Comment by ayush5harma** [comment]
> Can confirm, not working on PixelExperience with March security patch. (Pixel 2)

You don't get adaptive sound option under settings?

**Comment by ayush5harma** [comment]
> > Can confirm, not working on PixelExperience with March security patch. (Pixel 2)
> 
You get the option of adaptive sound under settings. Pixel 2XL user reported working it in his issue https://github.com/ayush5harma/PixelFeatureDrops/issues/26 so what is not working for you - option doesn't show or you feel the sound isn't adapted to the environment ?

And adaptive charging said many times and also there in many other blogs too that it  uses phone alarm,  funny but true. May they improve it.If you wanna cross check it's working set an alarm turn it on and check your battery stats while placing phone on charge over night.

**Comment by ayush5harma** [comment]
> I'm using pixel experience+ Android 11... I'm having the same issue...
> Device: Potter
> Module: March

**settings suggestions** got update from playstore?

**Comment by ayush5harma** [comment]
> > I'm using pixel experience+ Android 11... I'm having the same issue...
> > Device: Potter
> > Module: March
> 
> **settings suggestions** got update from playstore?

and your assistant ui is only not shown for assistant 2 ? without module using the shipped one ui shows for you?

**Comment by Kalyan-M** [comment]
> option doesn't show or you feel the sound isn't adapted to the environment ?

![Screenshot_20210329-032922_Settings](https://user-images.githubusercontent.com/24321730/112769535-416e0200-903f-11eb-8a45-f45b9cc7ba37.png)


The option doesn't show.

**Comment by ayush5harma** [comment]
> > option doesn't show or you feel the sound isn't adapted to the environment ?
> 
> ![Screenshot_20210329-032922_Settings](https://user-images.githubusercontent.com/24321730/112769535-416e0200-903f-11eb-8a45-f45b9cc7ba37.png)
> 
> The option doesn't show.

is there an update for settings suggestion over playstore? didn't u receive app updates after installing module?

**Comment by ayush5harma** [comment]
> > > option doesn't show or you feel the sound isn't adapted to the environment ?
> > 
> > 
> > ![Screenshot_20210329-032922_Settings](https://user-images.githubusercontent.com/24321730/112769535-416e0200-903f-11eb-8a45-f45b9cc7ba37.png)
> > The option doesn't show.
> 
> is there an update for settings suggestion over playstore? didn't u receive app updates after installing module? Search for adaptive sound from settings main page.

**Comment by ayush5harma** [comment]
> > > option doesn't show or you feel the sound isn't adapted to the environment ?
> > 
> > 
> > ![Screenshot_20210329-032922_Settings](https://user-images.githubusercontent.com/24321730/112769535-416e0200-903f-11eb-8a45-f45b9cc7ba37.png)
> > The option doesn't show.
> 
 is there an update for settings suggestion over playstore? didn't u receive app updates after installing module? Search for adaptive sound from settings main page.

**Comment by Kalyan-M** [comment]
`Settings Services` is already updated. Tried searching too.

**Comment by Viraj8456** [comment]
> > I'm using pixel experience+ Android 11... I'm having the same issue...
> > Device: Potter
> > Module: March
> 
> **settings suggestions** got update from playstore?

Yes I got and I updated it! Still the option is not showing up..

**Comment by ayush5harma** [comment]
> `Settings Services` is already updated. Tried searching too.



> > > I'm using pixel experience+ Android 11... I'm having the same issue...
> > > Device: Potter
> > > Module: March
> > 
> > 
> > **settings suggestions** got update from playstore?
> 
> Yes I got and I updated it! Still the option is not showing up..

Execute these from pc and check settings for the option:
```
adb shell
device_config put device_personalization_services AdaptiveAudio__enable_adaptive_audio true
device_config put device_personalization_services AdaptiveAudio__show_promo_notification true
```

**Comment by ayush5harma** [comment]
> > > I'm using pixel experience+ Android 11... I'm having the same issue...
> > > Device: Potter
> > > Module: March
> > 
> > 
> > **settings suggestions** got update from playstore?
> 
> Yes I got and I updated it! Still the option is not showing up..

> `Settings Services` is already updated. Tried searching too.


Check by flashing the updated module from release. Both Now playing and adaptive sound option missing should be fixed.

**Comment by Kalyan-M** [comment]
No luck with the updated module.

**Comment by ayush5harma** [comment]
> No luck with the updated module.

```
device_config put device_personalization_services AdaptiveAudio__enable_adaptive_audio true
```
does this showed option for you did you try ?

**Comment by Kalyan-M** [comment]
no that didn't either

**Comment by ayush5harma** [comment]
> no that didn't either

you're on pixel 2 running stock rom ? march security patch android 11?

**Comment by Kalyan-M** [comment]
> you're on pixel 2 running stock rom ? march security patch android 11?

Pixel Experience rom. Will probably switch back to stock. PE is a bit buggy.

**Comment by ayush5harma** [comment]
Replace the device personalization services from [here](https://www.apkmirror.com/apk/google-inc/device-personalization-services/device-personalization-services-r-14-playstore-oem-361994540-release/device-personalization-services-r-14-playstore-oem-361994540-android-apk-download/)

**Comment by siddharthalodha** [comment]
Hey i tried the file on my p2xl taimen running on march pixel experience rom. I don't see the adaptive sound option either.

**Comment by ayush5harma** [comment]
Use updated Release Files (Tested Working)
