### ISSUE TITLE
Google Camera Breaks

### ISSUE THREAD

**Issue by nash-an** [ayush5harma/PixelFeatureDrops#3]
Cannot open Google camera.

As soon as it finishes loading it crashes with "Camera keeps stopping."

**Comment by ayush5harma** [comment]
Which gcam port are you using and on what ROM ?
Is cam2api enabled?
Did you try any other gcam port from https://www.celsoazevedo.com/files/android/google-camera/ ?

**Comment by Viraj8456** [comment]
We are using mods only... For me it's camera PX 4.3...
And the fact is every app crashes which is trying to open camera... Instagram, WhatsApp,etc... Until we disable the module from magisks...

**Comment by ayush5harma** [comment]
Can you also tell me your device name and custom rom that you are using and Can you take logs of the scenario ?

**Comment by ayush5harma** [comment]
> We are using mods only... For me it's camera PX 4.3...
> And the fact is every app crashes which is trying to open camera... Instagram, WhatsApp,etc... Until we disable the module from magisks...



> Cannot open Google camera.
> 
> As soon as it finishes loading it crashes with "Camera keeps stopping."


Please flash v7.1 from release and check if that fixes your issue (July Patch).

If on older security patch and module version following ways may be opted to enable camera HAL3:

1. Install Termux from PlayStore (https://play.google.com/store/apps/details?id=com.termux&hl=en_IN)
2. Type - ``` su ```
3. Type - ``` setprop persist.vendor.camera.HAL3.enabled 1 ```
4. Reboot

or    

using some root explorer go to /data/adb/modules/P4XLProps open system.prop file in a note editor and save this line at the end of the file - ``` persist.vendor.camera.HAL3.enabled= 1 ``` then reboot.

**Comment by Viraj8456** [comment]
> Can you also tell me your device name and custom rom that you are using and Can you take logs of the scenario ?

Moto G5 Plus, PE+
July security patch is up for my phone,
I'll update tomorrow, as well as install the 7.1 pixel prop module

But I think camera HAL 3 was already enabled...🤔
Then too I'll check tomorrow.

**Comment by Viraj8456** [comment]
> > We are using mods only... For me it's camera PX 4.3...
> > And the fact is every app crashes which is trying to open camera... Instagram, WhatsApp,etc... Until we disable the module from magisks...
> 
> > Cannot open Google camera.
> > As soon as it finishes loading it crashes with "Camera keeps stopping."
> 
> Please flash v7.1 from release and check if that fixes your issue (July Patch).
> 
> If on older security patch and module version following ways may be opted to enable camera HAL3:
> 
> 1. Install Termux from PlayStore (https://play.google.com/store/apps/details?id=com.termux&hl=en_IN)
> 2. Type - `su`
> 3. Type - `setprop persist.vendor.camera.HAL3.enabled 1`
> 4. Reboot
> 
> or
> 
> using some root explorer go to /data/adb/modules/P4XLProps open system.prop file in a note editor and save this line at the end of the file - `persist.vendor.camera.HAL3.enabled= 1` then reboot.

Just installed Pixel props 7.1.
The issue still persists...

**Comment by ayush5harma** [comment]
> > > We are using mods only... For me it's camera PX 4.3...
> > > And the fact is every app crashes which is trying to open camera... Instagram, WhatsApp,etc... Until we disable the module from magisks...
> > 
> > 
> > > Cannot open Google camera.
> > > As soon as it finishes loading it crashes with "Camera keeps stopping."
> > 
> > 
> > Please flash v7.1 from release and check if that fixes your issue (July Patch).
> > If on older security patch and module version following ways may be opted to enable camera HAL3:
> > 
> > 1. Install Termux from PlayStore (https://play.google.com/store/apps/details?id=com.termux&hl=en_IN)
> > 2. Type - `su`
> > 3. Type - `setprop persist.vendor.camera.HAL3.enabled 1`
> > 4. Reboot
> > 
> > or
> > using some root explorer go to /data/adb/modules/P4XLProps open system.prop file in a note editor and save this line at the end of the file - `persist.vendor.camera.HAL3.enabled= 1` then reboot.
> 
> Just installed Pixel props 7.1.
> The issue still persists...
People are reporting camera issue in potter PE since june 21 build.Check this:  
https://forum.xda-developers.com/g5-plus/development/rom-pixel-experience-t3995717/page100  
It seems most likely to be an issue with the build 
Since when are you using the module with potter PE?Was this issue there with builds before 21st june?

**Comment by ayush5harma** [comment]
> > > We are using mods only... For me it's camera PX 4.3...
> > > And the fact is every app crashes which is trying to open camera... Instagram, WhatsApp,etc... Until we disable the module from magisks...
> > 
> > 
> > > Cannot open Google camera.
> > > As soon as it finishes loading it crashes with "Camera keeps stopping."
> > 
> > 
> > Please flash v7.1 from release and check if that fixes your issue (July Patch).
> > If on older security patch and module version following ways may be opted to enable camera HAL3:
> > 
> > 1. Install Termux from PlayStore (https://play.google.com/store/apps/details?id=com.termux&hl=en_IN)
> > 2. Type - `su`
> > 3. Type - `setprop persist.vendor.camera.HAL3.enabled 1`
> > 4. Reboot
> > 
> > or
> > using some root explorer go to /data/adb/modules/P4XLProps open system.prop file in a note editor and save this line at the end of the file - `persist.vendor.camera.HAL3.enabled= 1` then reboot.
> 
> Just installed Pixel props 7.1.
> The issue still persists...

People are reporting camera issue in potter PE since june 21 build.Check this:
https://forum.xda-developers.com/g5-plus/development/rom-pixel-experience-t3995717/page100
It seems most likely to be an issue with the build
Since when are you using the module with potter PE?Was this issue there with builds before 21st june?

**Comment by Viraj8456** [comment]
> > > > We are using mods only... For me it's camera PX 4.3...
> > > > And the fact is every app crashes which is trying to open camera... Instagram, WhatsApp,etc... Until we disable the module from magisks...
> > > 
> > > 
> > > > Cannot open Google camera.
> > > > As soon as it finishes loading it crashes with "Camera keeps stopping."
> > > 
> > > 
> > > Please flash v7.1 from release and check if that fixes your issue (July Patch).
> > > If on older security patch and module version following ways may be opted to enable camera HAL3:
> > > 
> > > 1. Install Termux from PlayStore (https://play.google.com/store/apps/details?id=com.termux&hl=en_IN)
> > > 2. Type - `su`
> > > 3. Type - `setprop persist.vendor.camera.HAL3.enabled 1`
> > > 4. Reboot
> > > 
> > > or
> > > using some root explorer go to /data/adb/modules/P4XLProps open system.prop file in a note editor and save this line at the end of the file - `persist.vendor.camera.HAL3.enabled= 1` then reboot.
> > 
> > 
> > Just installed Pixel props 7.1.
> > The issue still persists...
> 
> People are reporting camera issue in potter PE since june 21 build.Check this:
> https://forum.xda-developers.com/g5-plus/development/rom-pixel-experience-t3995717/page100
> It seems most likely to be an issue with the build
> Since when are you using the module with potter PE?Was this issue there with builds before 21st june?

I was using it since April build... This issue was still there....

**Comment by ayush5harma** [comment]
> > > > > We are using mods only... For me it's camera PX 4.3...
> > > > > And the fact is every app crashes which is trying to open camera... Instagram, WhatsApp,etc... Until we disable the module from magisks...
> > > > 
> > > > 
> > > > > Cannot open Google camera.
> > > > > As soon as it finishes loading it crashes with "Camera keeps stopping."
> > > > 
> > > > 
> > > > Please flash v7.1 from release and check if that fixes your issue (July Patch).
> > > > If on older security patch and module version following ways may be opted to enable camera HAL3:
> > > > 
> > > > 1. Install Termux from PlayStore (https://play.google.com/store/apps/details?id=com.termux&hl=en_IN)
> > > > 2. Type - `su`
> > > > 3. Type - `setprop persist.vendor.camera.HAL3.enabled 1`
> > > > 4. Reboot
> > > > 
> > > > or
> > > > using some root explorer go to /data/adb/modules/P4XLProps open system.prop file in a note editor and save this line at the end of the file - `persist.vendor.camera.HAL3.enabled= 1` then reboot.
> > > 
> > > 
> > > Just installed Pixel props 7.1.
> > > The issue still persists...
> > 
> > 
> > People are reporting camera issue in potter PE since june 21 build.Check this:
> > https://forum.xda-developers.com/g5-plus/development/rom-pixel-experience-t3995717/page100
> > It seems most likely to be an issue with the build
> > Since when are you using the module with potter PE?Was this issue there with builds before 21st june?
> 
> I was using it since April build... This issue was still there.... 

> > > > > We are using mods only... For me it's camera PX 4.3...
> > > > > And the fact is every app crashes which is trying to open camera... Instagram, WhatsApp,etc... Until we disable the module from magisks...
> > > > 
> > > > 
> > > > > Cannot open Google camera.
> > > > > As soon as it finishes loading it crashes with "Camera keeps stopping."
> > > > 
> > > > 
> > > > Please flash v7.1 from release and check if that fixes your issue (July Patch).
> > > > If on older security patch and module version following ways may be opted to enable camera HAL3:
> > > > 
> > > > 1. Install Termux from PlayStore (https://play.google.com/store/apps/details?id=com.termux&hl=en_IN)
> > > > 2. Type - `su`
> > > > 3. Type - `setprop persist.vendor.camera.HAL3.enabled 1`
> > > > 4. Reboot
> > > > 
> > > > or
> > > > using some root explorer go to /data/adb/modules/P4XLProps open system.prop file in a note editor and save this line at the end of the file - `persist.vendor.camera.HAL3.enabled= 1` then reboot.
> > > 
> > > 
> > > Just installed Pixel props 7.1.
> > > The issue still persists...
> > 
> > 
> > People are reporting camera issue in potter PE since june 21 build.Check this:
> > https://forum.xda-developers.com/g5-plus/development/rom-pixel-experience-t3995717/page100
> > It seems most likely to be an issue with the build
> > Since when are you using the module with potter PE?Was this issue there with builds before 21st june?
> 
> I was using it since April build... This issue was still there....

If the Camera works for you with module disabled take logs of camera activity with module enabled and without it.

**Comment by Viraj8456** [comment]
[logcat_08-06-2020_15-00-07.txt](https://github.com/ayush5harma/P4XLProps/files/5033966/logcat_08-06-2020_15-00-07.txt)

This is with Pixel props enabled. @ayush5harma
