### ISSUE TITLE
Redmi note 6 pro | No assistant UI | All ROMs

### ISSUE THREAD

**Issue by sanjeevstunner** [ayush5harma/PixelFeatureDrops#30]
No assistant UI, no matter the rom. I'm using pixel experience, and the assistant UI isn't showing up on it too. I used havoc, corvus, posp, aospk, derp, awaken, Octavi and a lot others, from my past issue post. Also tried the xda post you linked. 
There is no folder in /data/data as mentioned in that tutorial, also creating one manuall doesn't work. Please provide a solution for this.

Adaptive audio working IG on pe

![Screenshot_20210226-174213](https://user-images.githubusercontent.com/42514333/109299046-788f9e80-785a-11eb-853e-ef7e05720306.png)

**Comment by sanjeevstunner** [comment]
> No assistant UI, no matter the rom. I'm using pixel experience, and the assistant UI isn't showing up on it too. I used havoc, corvus, posp, aospk, derp, awaken, Octavi and a lot others, from my past issue post. Also tried the xda post you linked.
> There is no folder in /data/data as mentioned in that tutorial, also creating one manuall doesn't work. Please provide a solution for this.
> 
> Adaptive audio working IG on pe
> 
> ![Screenshot_20210226-174213](https://user-images.githubusercontent.com/42514333/109299046-788f9e80-785a-11eb-853e-ef7e05720306.png)

PS. Most roms used are on feb patch. Some of them are with jan patch

Waiting for a reply from you with a fox ASAP

**Comment by ayush5harma** [comment]
Is the issue still there with the latest release?

**Comment by ayush5harma** [comment]
> Is the issue still there with the latest release?

also try enrolling in Google app beta:  https://play.google.com/apps/testing/com.google.android.googlequicksearchbox
If disappearance is still there please take a log of the scene i.e run logcat and execute ok google command and post the log here.

**Comment by ayush5harma** [comment]
Use PixelFeatureDrop-Month-portedGA2 from release
