### ISSUE TITLE
Now playing not working

### ISSUE THREAD

**Issue by lologolo** [ayush5harma/PixelFeatureDrops#31]
device Lg g6 H870
android 11 Havoc OS
february patch

I've installed ambient services also as system app; now, in audio section appears "now playng" but when i click it, ambient services crash and doesn't allow me to use now playing feature

Locgat file says " /product/etc/ambient/matcher_tah.leveldb core shard not found."
So i extracted from another rom this file and placed in correct folder, now when i click on now playing there is no more crash but i can't still use now playing feature.

Also another error appears in logcat :  "Can't load /system/etc/firmware/music_detector . sound_model"

The logcat:
https://del.dog/uckolemoth.txt
https://del.dog/imicrilyxi.txt

**Comment by ayush5harma** [comment]
Try the updated release should work - https://github.com/ayush5harma/PixelFeatureDrops/releases/tag/r7
