### ISSUE TITLE
Android security updated sets after installing from March to December and ctsProfile fails after that

### ISSUE THREAD

**Issue by Matthew-X** [ayush5harma/PixelFeatureDrops#35]
I tried to install the module and after i install it i see that security update changes once i install it and ctsProfile fails. Did i do something wrong ?

**Comment by ayush5harma** [comment]
I don't understand what are u asking for? Do you mean Google Play System Update?

In any case if you're using the right module i.e corresponding to your ROM security patch date and safety net still fails refer  - https://github.com/ayush5harma/PixelFeatureDrops#instructions-for-safetynet-
