### ISSUE TITLE
PixelFeatureDrops and Aux Lenses

### ISSUE THREAD

**Issue by MikuDroid** [ayush5harma/PixelFeatureDrops#37]
After installing released props my camera app can't detect /switch to aux lenses (i have macro and ultra wide lens). Is there any way to enable it while still using the props? I assume system.prop tied with aux lens detection, what should i change? My device is Redmi Note 8, running ArrowOS Android 11.

**Comment by ayush5harma** [comment]
- If you are using gcam port try loading appropriate config file for the gcam you are using. Below is the link to configs for wyroczen's google camera port for your device.
https://www.celsoazevedo.com/files/android/google-camera/f/configs-wyroczen-03/

- If you're using miui cam port which checks for device fingerprint you have to spoof the device fingerprint for miuicam using edxposed module (https://github.com/ikws4/WeiJu) to make it work (you may check video here https://github.com/ayush5harma/PixelFeatureDrops/issues/10#issuecomment-701601857).You can get these variable values from your stcok build.prop file.

**Comment by MikuDroid** [comment]
Thanks! gonna try. Closing the issue.
