### ISSUE TITLE
Credits?

### ISSUE THREAD

**Issue by 0x11DFE** [ayush5harma/PixelFeatureDrops#4]
Hello, i shared the exact same props few days ago on https://t.me/PixelProps
If you are using these please provide a referring link to the server.

**Comment by ayush5harma** [comment]
The prop values are taken from  coral tree in the android dumps which are updated every month at gitlab :   
https://git.rip/dumps/google/coral/-/tree/coral-user-10-QQ3A.200705.002-6506677-release-keys/
