### ISSUE TITLE
pixel one or xl? 

### ISSUE THREAD

**Issue by billpage911** [ayush5harma/PixelFeatureDrops#45]
can  we get a support for pixel one or xl ? ...for original quality

**Comment by ayush5harma** [comment]
Will work on Custom ROM running android 11 and using security patch corresponding module on pixel 1 or xl

**Comment by nonyonah** [comment]
Will it work on non custom aosp rom?

**Comment by ayush5harma** [comment]
> Will it work on non custom aosp rom?

some things may work simply because of change in fingerprint otherwise no.It all depends on how much OEM influenced the AOSP stock is.

**Comment by nonyonah** [comment]
I use an android one device i.e pure aosp, so does that count?

**Comment by zhyq118** [comment]
Will it work on OxygenOS 11 ?

**Comment by ayush5harma** [comment]
> I use an android one device i.e pure aosp, so does that count?



> Will it work on OxygenOS 11 ?

it won't work on OEM ROMs except for the one by google that too with corresponding security patch.
