### ISSUE TITLE
Ok Google isn't available for my language (English US only)

### ISSUE THREAD

**Issue by Skyblueborb** [ayush5harma/PixelFeatureDrops#49]
When I try to setup "Ok Google" in the Google app it doesn't let me.

**Comment by ayush5harma** [comment]
It's not dead due to the module. If you doubt check by removing the module and try setting it up. If it doesn't work normally it is due to issue with ROM.

**Comment by Rihcus** [comment]
I have a similar issue. The interesting thing I noticed is when running the non preview mode (I have English and HIndi as my assitant languages) "Ok Google" works just fine. However when I remove Hindi and google assitant switches to the new mode "Ok Google" doesn't work. Additionally on the new google assistant there is a delay before it is able to undestand my command even when summoned manually. I found out that the new google assistant tries to transcribe commands locally on device and send reponses to cloud for faster processing but if the device fails to understand the command it rerecords the command and sends your voice to the cloud to be transcribed and works normally.

I wonder if the lack of the device personalization service on certain ROM's like lineage os would pose a problem. (Sry for long post)

**Comment by Rihcus** [comment]
> When I try to setup "Ok Google" in the Google app it doesn't let me.

If you don't mind me asking what phone/rom are you using? Also does your phone have device personalization service installed?

**Comment by IMSoley** [comment]
@ayush5harma "This feature is unavailable for this language" - This is what shows on my phone after installing the module.

Redmi Note 9 (Merlin), A11
Nusantara v3.0 (Rotterdam)

Language set to English everywhere except Gboard input method (Bangla & English).

**Comment by ayush5harma** [comment]
> I have a similar issue. The interesting thing I noticed is when running the non preview mode (I have English and HIndi as my assitant languages) "Ok Google" works just fine. However when I remove Hindi and google assitant switches to the new mode "Ok Google" doesn't work. Additionally on the new google assistant there is a delay before it is able to undestand my command even when summoned manually. I found out that the new google assistant tries to transcribe commands locally on device and send reponses to cloud for faster processing but if the device fails to understand the command it rerecords the command and sends your voice to the cloud to be transcribed and works normally.
> 
> I wonder if the lack of the device personalization service on certain ROM's like lineage os would pose a problem. (Sry for long post)

Hi Since you mentioned preview mode are you using assistantconfig.zip ?

**Comment by ayush5harma** [comment]
> @ayush5harma "This feature is unavailable for this language" - This is what shows on my phone after installing the module.
> 
> Redmi Note 9 (Merlin), A11
> Nusantara v3.0 (Rotterdam)
> 
> Language set to English everywhere except Gboard input method (Bangla & English).

Hi please check and tell with this -   
https://github.com/ayush5harma/PixelFeatureDrops/releases/download/07052021/JulyPixelFeatureDrop.zip

**Comment by ayush5harma** [comment]
> > When I try to setup "Ok Google" in the Google app it doesn't let me.
> 
> If you don't mind me asking what phone/rom are you using? Also does your phone have device personalization service installed?

cherishOS on rmx2001. Yes it's there due to gapps package build.

**Comment by IMSoley** [comment]
> > @ayush5harma "This feature is unavailable for this language" - This is what shows on my phone after installing the module.
> > Redmi Note 9 (Merlin), A11
> > Nusantara v3.0 (Rotterdam)
> > Language set to English everywhere except Gboard input method (Bangla & English).
> 
> Hi please check and tell with this -
> https://github.com/ayush5harma/PixelFeatureDrops/releases/download/07052021/JulyPixelFeatureDrop.zip

No luck!

**Comment by ayush5harma** [comment]
Hi please check with ROM developer. The OK google hotword detection got recently fixed in rmx2001.Your device developer might have as well disabled it due to issues in telephony. If not reopen. Thanks.
