### ISSUE TITLE
Front camera pops

### ISSUE THREAD

**Issue by AveyBD** [ayush5harma/PixelFeatureDrops#5]
I am on Redmi K20 Pro. Every time i reboot is popa the camera out. 
i have tried on Evox rom. v
The rom developer said **screen attention being enabled by the module.** 
please fix the issue. 
Thanks

**Comment by ayush5harma** [comment]
Screen attention is not there in recent sources of those ROM's, it used to be in early days.
Even if you get an option to enable screen attention via settings (unlikely in recent builds) post module installation it doesn't get enabled by default, one has to toggle the switch,give device personalisation services the camera permission to turn it on and make it work and if screen attention is enabled the pop out camera will stay out.

Being said that if you're so sure that it's the screen attention causing that then you can either disable it via setting by searching for screen attention or if that is not shown you can go to permission manager and remove camera permission from device personalisation services.
