### ISSUE TITLE
Nothing is happening 

### ISSUE THREAD

**Issue by themikuik** [ayush5harma/PixelFeatureDrops#50]
I flashed everything but it's like nothing changed for my phone (mi mix 3 on pe) any solutions?

**Comment by Rihcus** [comment]
Well the most basic test to check if the mod is partially working is in your system settings your device model should say something like Pixel 5. Second make sure you don't install this module with magisk props config as its possible they may conflict. 

Aside from that you need to be more specific on what parts isn't working.

**Comment by ayush5harma** [comment]
> I flashed everything but it's like nothing changed for my phone (mi mix 3 on pe) any solutions?


- Check if  Module version  corresponds to android security patch of your custom ROM.
- Install updates via playstore
- Refer readme for any feature drop specifics
- If GA2 is not working try AssiatantFix from release page if still not work report.
- Adaptive charges is known to not work.

Reopen if needed
