### ISSUE TITLE
It breaks the camera

### ISSUE THREAD

**Issue by GiovannaRAY** [ayush5harma/PixelFeatureDrops#51]
Hey love your module but unfortunately it breaks the camera, would be awesome if you made a optional version that doesn't give the camera features. That way would help anyone with camera problems. Cheers.

**Comment by ayush5harma** [comment]
Hi please  mention the device and ROM

**Comment by cantekinerdogan** [comment]
Hello, i am having the same problem.  MIUI stock camera not working.

Device:curtana

Rom:xiaomi.eu rom stabil 12.2

**Comment by sucami82882** [comment]
i have that problem too, every rom (aosp and not) i recently used on my poco x3 (surya) had big camera issues after installed this module, please remove the camera feature or just let us choose if activate it or not

**Comment by ayush5harma** [comment]
> Hello, i am having the same problem. MIUI stock camera not working.
> 
> Device:curtana
> 
> Rom:xiaomi.eu rom stabil 12.2

it's for AOSP roms

**Comment by ayush5harma** [comment]
> i have that problem too, every rom (aosp and not) i recently used on my poco x3 (surya) had big camera issues after installed this module, please remove the camera feature or just let us choose if activate it or not

There aren't any camera features. The change in fingerprint might be breaking your gcam. Which gcam have you used?

**Comment by prova88838** [comment]
hello i'm on surya too, I tested the module in many aosp roms and i used many gcams with lots of xmls, i had all the time the same problem. photo shooted had always a green tint, please fix this cause i love this module

**Comment by prova88838** [comment]
anx camera has this problem too

**Comment by Sgr31** [comment]
I'm on Redmi Note 10 pro. I flashed ANX camera zip after flashing 'PixelFeatureDrops' module. Magisk flash log showed that ANX zip recognized my device as 'Redfin' (Pixel5).

**Comment by ayush5harma** [comment]
Anx camera is for miui camera port for xiaomi devices which is why it must have failed install reading Redfin from build.prop.

Flashing the zip before will install anx camera but it will cause trouble while using due to same reason. Will update the guide regarding selectively overriding build.prop for such apps.

Also to make sure it is only for custom ROMs and not MIUI. Just saying because of previous issues.
