### ISSUE TITLE
Google Photos not backing up, says "Device too hot"

### ISSUE THREAD

**Issue by nimishmathur1997** [ayush5harma/PixelFeatureDrops#52]
I installed this module on my OnePlus 6 running oxygen OS11 beta 1. After that google photos app is not backing up photos. There is a constant error message saying "Device too hot" even when the device is not even warm. I have tried updating the photos app, clearing it's data, force stopping it....Nothing worked.

**Comment by ayush5harma** [comment]
for AOSP custom ROMs.
