### ISSUE TITLE
bootloop on crDroid 7.9

### ISSUE THREAD

**Issue by Orel6505** [ayush5harma/PixelFeatureDrops#55]
when i trying flashing your PixelFeatureDrops, i got bootloop.

crDroid 7.9
Beyond1lte - Samsung Galaxy S10

**Comment by avishaiDV** [comment]
same here ^^

crDroid 7.9 – Beyond0lte (S10e)

**Comment by ayush5harma** [comment]
Was experimenting by adding hardware related audio config as an attempt to fix hotword for some users. Will revert asap. Thanks for reporting.
