### ISSUE TITLE
Brightness slider broken on OxygenOS 11

### ISSUE THREAD

**Issue by DavidScann** [ayush5harma/PixelFeatureDrops#56]
I'll start by saying that I acknowledge the fact that PixelFeatureDrops are designed to be used with AOSP Custom ROMs rather than stock manufacturer ROMs, and if this issue is discarded for that reason I fully understand.

Device information: OnePlus 8 Pro / Oxygen OS build 11.0.5.5.IN11AA

Issue: Brightness slider not affecting screen brightness.
Description: You can slide the slider around, but it just wouldn't change anything. One notable thing is that the issue seems to be resolved on the lockscreen. Doesn't work anywhere else though.

**Comment by Amsal1** [comment]
Facing same issue with brightness slider not working on Device: OnePlus 8T / Oxygen OS build 11.0.8.14.KB05DA

Using JunePatch

**Comment by theoneandonly-vector** [comment]
same on OnePlus 8 pro

**Comment by rrevanth** [comment]
You have to edit the spoof.prop or system.prop to remove these two lines to fix the brightness issue

ro.product.vendor.device=redfin
ro.product.vendor.manufacturer=Google

**Comment by ayush5harma** [comment]
Selectively overiding build.prop values for SystemUI using LSposed module Weibu will solve the issue too. The benefit being selective overriding will not detain other google features from enabling which editing the prop will. Will update the guide regarding same.

**Comment by Amsal1** [comment]
> Selectively overiding build.prop values for SystemUI using LSposed module Weibu will solve the issue too. The benefit being selective overriding will not detain other google features from enabling which editing the prop will. Will update the guide regarding same.

Sure. Would be great to have a guide on this. Thanks a lot!

**Comment by duramato** [comment]
`Selectively overiding build.prop values for SystemUI using LSposed module Weibu will solve the issue too.` Which module is this `Weibu`? I've tried googling it but I'm not finding it.
