### ISSUE TITLE
Causing bootloop after installing Pixel feature drop on miui

### ISSUE THREAD

**Issue by Shivaji4** [ayush5harma/PixelFeatureDrops#57]
i have flashed PixelFeatureDrop module in MI 11X on MIUI 12.5.2 after rebooting its auto booting up to twrp after showing the lockscreen 
i tried removing it from module section and device starts booting up normally 
How to fix this??

**Comment by ayush5harma** [comment]
The Xiaomi module is for Xiaomi devices running custom ROMs which earlier faced camera pop up bug during boot. It is not meant for MIUI. Will add this. Sorry about the inconvenience.
