### ISSUE TITLE
Causing bootloop after installed August version

### ISSUE THREAD

**Issue by ralph950412** [ayush5harma/PixelFeatureDrops#58]
I have tested many versions, only august version causes bootloop
LineageOS 18.1 (clover)

**Comment by Orel6505** [comment]
Same

**Comment by ralph950412** [comment]
> Same

What rom and device are you using

**Comment by Orel6505** [comment]
crDroid 7.9 Beyond1lte

**Comment by ayush5harma** [comment]
Was experimenting by adding hardware related audio config as an attempt to fix hotword for some users. Will revert asap. Thanks for reporting.
