### ISSUE TITLE
flashlight and other stuff not working in MIUI 12.5

### ISSUE THREAD

**Issue by aliakmohiuddin** [ayush5harma/PixelFeatureDrops#59]
the flashlight isn't working when you install the hal3 or Xiaomi module. only flashlight working is when you're using camera. same thing with double tap to wake up/sleep, and face unlock are both absent

**Comment by ayush5harma** [comment]
The Xiaomi module is for Xiaomi devices running custom ROMs. The module is not meant for MIUI.
