### ISSUE TITLE
Confusing module description in README

### ISSUE THREAD

**Issue by joeldemars** [ayush5harma/PixelFeatureDrops#61]
The README contains a line that says:
`The following features enable on an AOSP custom ROM using pixel's system UI with gapps installed post module installation.`
I misinterpreted this to mean that you should install Gapps after installing the module, which conflicts with how the Gapps distributors say to install Gapps immediately after flashing the custom. Eventually I realized that I was reading the sentence wrong.

**Comment by ayush5harma** [comment]
Thanks
