### ISSUE TITLE
Brightness issues oneplus 8 oxygen os 11.0.9.9.IN21DA

### ISSUE THREAD

**Issue by Rihcus** [ayush5harma/PixelFeatureDrops#65]
Hello  having brightness issues screen stuck on dim when pixelfeaturedrops is enabled. The strange part is the brightness issue is only present when the phone is unlocked (no issues in lock screen).

**Comment by Rihcus** [comment]
I was kinda able to fix the issue by nuking the system.prop. Google photos unlimited photos works I'm not sure about the other modules.

I delted all the text in system.prop and left # This file will be read by resetprop

**Comment by duramato** [comment]
I'm also having this issue. Isn't this an issue with the magisk module?

**Comment by duramato** [comment]
This seems related to this: https://github.com/ayush5harma/PixelFeatureDrops/issues/56

**Comment by Rihcus** [comment]
> I'm also having this issue. Isn't this an issue with the magisk module?
Yeah that was the problem I couldn't get the lsposed module to work. As a side note does Google call screen work?

**Comment by duramato** [comment]
Which LSPosed module?

**Comment by Rihcus** [comment]
Weibu #56 

> Which LSPosed module?

**Comment by duramato** [comment]
Got a link for it? Can't find it anywhere by googling

**Comment by Rihcus** [comment]
> Got a link for it? Can't find it anywhere by googling

https://github.com/ayush5harma/PixelFeatureDrops/issues/63#issuecomment-902616723
