### ISSUE TITLE
Camera force close on Pixel 2XL (Aug 10)

### ISSUE THREAD

**Issue by Frechen** [ayush5harma/PixelFeatureDrops#7]
Tested both modules on non-custom ROM, August patch, and camera fc.
After deactivating the module, camera works fine again.

Any idea to make it work with stock?

**Comment by ayush5harma** [comment]
Updated the release files.
You'll need to remove the flashed module and redownload **P4XLProps.zip** from release section and then flash and check.

**Comment by Frechen** [comment]
Thanks for the update.

I Installed the HAL3 version and camera works fine.

However, I'm not sure Assistant 2 is running, cause continous conversation doesn't work, even if set to "English US"

**Comment by Frechen** [comment]
Sad, still fc.

Camera opens and after 1 second fc.

I can provide logcat


08-21 10:25:29.723 E/InputDispatcher(1306): Window handle Window{f3dd134 u0 Application Error: com.google.android.GoogleCameraEng} has no registered input channel

**Comment by ayush5harma** [comment]
> Thanks for the update.
> 
> I Installed the HAL3 version and camera works fine.
> 
> However, I'm not sure Assistant 2 is running, cause continous conversation doesn't work, even if set to "English US"

You don't need to flash the HAL3 , just use the normal P4XLProps  .Your ROM already has cam2api enabled as it's stock pixel you mentioned.
To enabled assistant install ngaresources.apk (link in readme) after module install, then clear google app's data then trigger the google assistant  which will ask to download additional update for assistant v2 . To enable continued conversation follow readme.

**Comment by ayush5harma** [comment]
> Sad, still fc.
> 
> Camera opens and after 1 second fc.
> 
> I can provide logcat
> 
> 08-21 10:25:29.723 E/InputDispatcher(1306): Window handle Window{f3dd134 u0 Application Error: com.google.android.GoogleCameraEng} has no registered input channel

You using P4XLProps or P4XLProps-HAL3 ?

**Comment by Frechen** [comment]
Hi!

Thanks for your help.
I tried both versions, but cam fc, even with P4XLProps :(

**Comment by ayush5harma** [comment]
> Hi!
> 
> Thanks for your help.
> I tried both versions, but cam fc, even with P4XLProps :(

Hi, i just want you to check whether camera2api breaks for you after you flash the module.You can do so by simply installing this app 
	
**Camera2 API Probe**
https://play.google.com/store/apps/details?id=com.airbeat.device.inspector&hl=en_IN

and send the screenshot here

**Comment by ayush5harma** [comment]
closed with https://github.com/ayush5harma/P4XLProps/issues/10#issuecomment-701601857
