### ISSUE TITLE
Lag issue

### ISSUE THREAD

**Issue by ios7jbpro** [ayush5harma/PixelFeatureDrops#8]
Los 17.1 closed beta unofficial.(lg g4)

After installing this module, in around every 5 minutes device gets incredible laggy, then fixes around a minute or so.

**Comment by ayush5harma** [comment]
You mention it to be an unofficial build . What kernel is being used ?

**Comment by ios7jbpro** [comment]
3.10.108-g1a0db9c9a837db-dirty
#7 Tue Aug 4 20:54:03 EEST 2020 it says on settings
