### ISSUE TITLE
Screen goes dim 

### ISSUE THREAD

**Issue by ryanlowen81** [ayush5harma/PixelFeatureDrops#9]
Every time I install this on the oneplus 8 pro. It has a dim screen and doesn't get bright

**Comment by ayush5harma** [comment]
> Every time I install this on the oneplus 8 pro. It has a dim screen and doesn't get bright

Try to be descriptive with things like which custom ROM are you using , and what do you mean by **doesn't get bright**? Are you talking of adaptive brightness not working or brightness slider not working for you.
